upx:
  - enabled: false
    compress: best

archives:
- format: binary

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - freebsd
      - openbsd
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
